Rapsys\UserBundle\Entity\User:
    type: mappedSuperclass
    repositoryClass: Rapsys\UserBundle\Repository\UserRepository
#   table: users
    id:
        id:
            type: integer
            generator: 
                strategy: AUTO
            options:
                unsigned: true
    fields:
        mail:
            type: string
            unique: true
            length: 254
        forename:
            type: string
            length: 32
            nullable: true
        surname:
            type: string
            length: 32
            nullable: true
        password:
            type: string
            length: 60
        active:
            type: boolean
            options:
                default: true
        enable:
            type: boolean
            options:
                default: true
        created:
            type: datetime
        updated:
            type: datetime
    manyToOne:
        civility:
            targetEntity: Civility
            inversedBy: users
    manyToMany:
        groups:
            targetEntity: Group
            inversedBy: users
#see if usefull: https://stackoverflow.com/questions/34523699/how-to-extend-doctrine-entity-in-another-bundle
#           joinTable:
#               name: users_groups
#               joinColumns:
#                   id:
#                       name: user_id
#               inverseJoinColumns:
#                   id:
#                       name: group_id
    lifecycleCallbacks:
        preUpdate: ['preUpdate']
