#Service configuration
services:
    #Register security context service
    rapsys_user.access_decision_manager:
        class: 'Symfony\Component\Security\Core\Authorization\AccessDecisionManager'
        public: true
        arguments: [ [ '@security.access.role_hierarchy_voter' ] ]
    #Register default controller
    Rapsys\UserBundle\Controller\DefaultController:
        arguments: [ '@service_container', '@doctrine', '@security.user_password_hasher', '@logger', '@mailer.mailer', '@doctrine.orm.default_entity_manager', '@router', '@rapsys_pack.slugger_util', '@request_stack', '@translator', '@twig' ]
        tags: [ 'controller.service_arguments' ]
    #Register Authentication success handler
    security.authentication.success_handler:
        class: 'Rapsys\UserBundle\Handler\AuthenticationSuccessHandler'
        arguments: [ '@router', {} ]
    #Register Authentication failure handler
    security.authentication.failure_handler:
        class: 'Rapsys\UserBundle\Handler\AuthenticationFailureHandler'
        arguments: [ '@http_kernel', '@security.http_utils', {}, '@logger', '@service_container', '@doctrine', '@router', '@rapsys_pack.slugger_util', '@security.csrf.token_manager' ]
    #Register default logout listener
    security.logout.listener.default:
        class: 'Rapsys\UserBundle\Listener\LogoutListener'
        arguments: [ '@service_container', '/', '@router' ]
    #Register security user checker
    security.user_checker:
        class: 'Rapsys\UserBundle\Checker\UserChecker'
