#Service configuration
services:
    #Register security context service
    rapsys_user.access_decision_manager:
        class: 'Symfony\Component\Security\Core\Authorization\AccessDecisionManager'
        public: true
        arguments: [ [ '@security.access.role_hierarchy_voter' ] ]
    #Register default controller
    Rapsys\UserBundle\Controller\DefaultController:
        arguments: [ '@service_container', '@router', '@translator' ]
        autowire: true
        tags: [ 'controller.service_arguments' ]
    #Register Authentication success handler
    security.authentication.success_handler:
        class: 'Rapsys\UserBundle\Handler\AuthenticationSuccessHandler'
        arguments: [ '@router', {} ]
    #Register logout success handler
    security.logout.success_handler:
        class: 'Rapsys\UserBundle\Handler\LogoutSuccessHandler'
        #XXX: second argument will be replaced there by kernel.mail.logout.target
        #XXX: vendor/symfony/security-bundle/DependencyInjection/SecurityExtension.php +360
        arguments: [ '@service_container', '/', '@router' ]
