#Service configuration
services:
    #Register security context service
    rapsys_user.access_decision_manager:
        class: 'Symfony\Component\Security\Core\Authorization\AccessDecisionManager'
        public: true
        arguments: [ [ '@security.access.role_hierarchy_voter' ] ]
    #Register default controller
    Rapsys\UserBundle\Controller\DefaultController:
        arguments: [ '@service_container', '@router', '@translator' ]
        autowire: true
        tags: [ 'controller.service_arguments' ]
    #Register Authentication success handler
    security.authentication.success_handler:
        class: 'Rapsys\UserBundle\Handler\AuthenticationSuccessHandler'
        arguments: [ '@router', {} ]
    #Register Authentication failure handler
    security.authentication.failure_handler:
        class: 'Rapsys\UserBundle\Handler\AuthenticationFailureHandler'
        arguments: [ '@http_kernel', '@security.http_utils', {}, '@logger', '@service_container', '@router', '@rapsys_pack.slugger_util']
    #Register logout success handler
    security.logout.success_handler:
        class: 'Rapsys\UserBundle\Handler\LogoutSuccessHandler'
        arguments: [ '@service_container', '/', '@router' ]
    #Register security user checker
    security.user_checker:
        class: 'Rapsys\UserBundle\Checker\UserChecker'
