rapsys_user_confirm:
    path: /confirm/{mail}/{extra}/{hash}
    controller: Rapsys\UserBundle\Controller\DefaultController::registerMail
    requirements:
        mail: '[a-zA-Z0-9=_-]+'
        extra: '[a-zA-Z0-9=_-]+'
        hash: '[a-zA-Z0-9=_-]+'
    methods: GET|POST

rapsys_user_login:
    path: /login/{mail}/{hash}
    controller: Rapsys\UserBundle\Controller\DefaultController::login
    defaults:
        mail: ~
        hash: ~
    requirements:
        mail: '[a-zA-Z0-9=_-]+'
        hash: '[a-zA-Z0-9=_-]+'
    methods: GET|POST

rapsys_user_logout:
    path: /logout
    methods: GET

rapsys_user_recover:
    path: /recover/{mail}/{pass}/{hash}
    controller: Rapsys\UserBundle\Controller\DefaultController::recover
    defaults:
        mail: ~
        pass: ~
        hash: ~
    requirements:
        mail: '[a-zA-Z0-9=_-]+'
        pass: '[a-zA-Z0-9=_-]+'
        hash: '[a-zA-Z0-9=_-]+'
    methods: GET|POST

rapsys_user_register:
    path: /register/{field}/{hash}
    controller: Rapsys\UserBundle\Controller\DefaultController::register
    defaults:
        field: ~
        hash: ~
    requirements:
        field: '[a-zA-Z0-9=_-]+'
        hash: '[a-zA-Z0-9=_-]+'
    methods: GET|POST

rapsys_user_edit:
    path: /user/{mail}
    controller: Rapsys\UserBundle\Controller\DefaultController::edit
    requirements:
        mail: '[a-zA-Z0-9=_-]+'
    methods: GET|POST

rapsys_user_index:
    path: /
    methods: GET
