rapsys_user_confirm:
    path: /confirm/{hash}/{mail}
    controller: Rapsys\UserBundle\Controller\DefaultController::registerMail
    requirements:
        hash: '[a-zA-Z0-9=_-]+'
        mail: '[a-zA-Z0-9=_-]+'
    methods: GET|POST

rapsys_user_login:
    path: /login/{hash}/{mail}
    controller: Rapsys\UserBundle\Controller\DefaultController::login
    defaults:
        hash: ~
        mail: ~
    requirements:
        hash: '[a-zA-Z0-9=_-]+'
        mail: '[a-zA-Z0-9=_-]+'
    methods: GET|POST

rapsys_user_logout:
    path: /logout
    methods: GET

rapsys_user_recover:
    path: /recover/{hash}/{pass}/{mail}
    controller: Rapsys\UserBundle\Controller\DefaultController::recover
    defaults:
        hash: ~
        pass: ~
        mail: ~
    requirements:
        hash: '[a-zA-Z0-9=_-]+'
        pass: '[a-zA-Z0-9=_-]+'
        mail: '[a-zA-Z0-9=_-]+'
    methods: GET|POST

rapsys_user_register:
    path: /register/{hash}/{field}/{mail}
    controller: Rapsys\UserBundle\Controller\DefaultController::register
    defaults:
        hash: ~
        field: ~
        mail: ~
    requirements:
        hash: '[a-zA-Z0-9=_-]+'
        field: '[a-zA-Z0-9=_-]+'
        mail: '[a-zA-Z0-9=_-]+'
    methods: GET|POST

rapsys_user_edit:
    path: /user/{hash}/{mail}
    controller: Rapsys\UserBundle\Controller\DefaultController::edit
    requirements:
        hash: '[a-zA-Z0-9=_-]+'
        mail: '[a-zA-Z0-9=_-]+'
    methods: GET|POST

rapsys_user_index:
    path: /
    methods: GET
